apiVersion: v1
kind: Secret
metadata:
  name: {{ template "directus.fullname" . }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  key: {{ .Values.config.key | quote }}
  secret: {{ .Values.config.secret | quote }}
  db_password: {{ .Values.config.dbPassword | quote }}
  admin_password: {{ .Values.config.adminPassword | quote }}
