images:
  directus:
    repository: directus/directus
    tag: v9-rc.61

config:
  clusterType: rke
  imagePullPolicy: Always
  updateStrategy: Recreate
  directus:
    baseUrl: ''
    hostname: ''
    resources:
      enabled: 'false'
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
  key: ''
  secret: ''
  dbClient: 'pg'
  dbHost: ''
  dbPort: '5432'
  dbDatabase: ''
  dbUser: ''
  dbPassword: ''
  cacheEnabled: 'false'
  cacheStore: 'redis'
  cacheRedis: ''
  adminEmail: 'admin@example.com'
  adminPassword: 'd1r3ctu5'

service:
  directus:
    type: ClusterIP
    externalTrafficPolicy: Cluster
    nodePorts:
      http:
    lbPorts:
      http: 80

ingress:
  directus:
    certificate: ''
    enabled: false
    hostname: ''
    tls: false
    issuer:
      name: letsencrypt-staging

persistence:
  accessMode: ReadWriteOnce
  enabled: false
  storageClass: ''
  existingClaim:
    directus: ''
  size:
    directus: 1Gi

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
